### PR TITLE
Reimplementing features from RoboCup 2023

### PR DESCRIPTION
**Pull request by Wanchai290**
# Description & content
This PR ensures we are adding most of the features that we had during RoboCup 2023 back into the `main` branch, to have a 
proper starting point for the next competition in 2024.

Features are extracted from [rbc-last-match](/NAMeC-SSL/CRAbE/tree/rbc-last-match). It mostly serves as a re-collection of small commits representing each feature re-implemented. Whether the pull request is accepted or not is not important, but helps identifying the features we have to merge back into `main`.

Some features have deliberately not been re-implemented as they require a re-design or thorough discussion in the team about the software's architecture, and are listed down below.

Status : <span style="color:green">**FINISHED**</span>

### GameManager and strategies
- File `crabe_decision/src/manager/game_manager.rs`
- Folder `crabe_decision/src/strategy/`

The decision pipeline cannot switch from one strategy to another as we had identified during the competition. This led to "hacksy" ways of changing the strategy which would not be suitable on the long-term.

### State machine (GameController Pre/Post filters)
I don't have enough knowledge on my own to judge whether what we had was valid or not, I'd like to let someone handle it for me.

### Modify MoveTo command + Obstacle avoidance
We have to delve deeper into the high-level command and the actual movement of the robot that happens in its embedded software. Also, setting a given initialization signature for the MoveTo command (`MoveTo::new()`) would help us not having to crawl in the whole codebase to modify any call to it when MoveTo receives a change.

### Receive filtered data from AutoRefs
Related pull request :
- #33

AutoReferees now publish filtered data from the vision, such as robot speed and acceleration.
Was not implemented in the end during the competition, but could make a huge difference in our decision-taking and algorithms.

### Negative coordinates always point towards our side of the field
IIRC @Jossl123 implemented a filter and something else that would affect the coordinates. This would mean that sending a robot to positive coordinates would put the robot in the enemy's side of the field.  
Haven't identified yet which commits and PRs are related to it.

### Whatever resides in `crabe_filter/src/pre_filter/*`
never worked on the filters before so I need help figuring it out  
you can check for yourself using the following command
```bash
git checkout feats-from-rbc
git diff rbc-last-match crates/crabe_filter/src/pre_filter/*
```
Note that this will not display the files that were added on the target branch.

### Data about the goal coordinates
Related commit :
- d68191b91ebdc6921b3b521ed3a2157ab32cbcfa

### More points about goal area
Related commits : 
- 21c34976013976e0c52c39d152efe1e5c197f583
- d68191b91ebdc6921b3b521ed3a2157ab32cbcfa
Instead of only top-left and bottom-right, you get more points like bottom-left and center.

### Everything in `crabe_math`
Didn't write the functions nor the tests, so I'll let it to ya

### Move `gc` option to common config
Related commit :
- 964ede4af2bb68d52e32a29a81561e1aabc01468
@EtienneSchmitz it's yours, not sure about its importance so I'll leave it to you

## Features being added
Note that not all features will be explained below (because I was too lazy at first and wrote it in the commit message instead)

### [Done] Improve refresh rate precision
Related commit and PR:
- #68
- 634f1fe655faf3846fd8e923f42af94577a7ac68

### [Done] Filter one specific side of the field
Related pull requests :
- #11
- #21 (specifically 220714e5798e027adfd8fb4c041942b442a77594)
- #25

### CODE REVIEW

**Review by dalestee — APPROVED** [review]

**Review by dalestee — APPROVED** [review]

**Comment by Wanchai290** [comment]
had to force-push once to overwrite the commit, so it includes original commit author, sorry

**Comment by Wanchai290** [comment]
@dalestee @Jossl123 @EtienneSchmitz @benjaminchew4 @Bedeux @Nuno-Moreira-Ribeiro 
This PR is finished, hopefully I identified all the features we had during the RoboCup 2023. There's a lot that I didn't yet implement here because I cant judge alone if they are good or not, so please have a look here so you can use this as reference to implement the identified features.
I've done my best to try to not miss any, but since everyone has a different point of view on the work we've done, we could identify missing features faster.

Everything builds on my machine but I haven't thoroughly tested everything. I lack time to do it so I need help

**Comment by Wanchai290** [comment]
As @Jossl123 mentioned, I have used the wrong branch as work reference. A more recent branch called [rbc-final-version](https://github.com/NAMeC-SSL/CRAbE/tree/rbc-final-version) was the one that had the latest features. The only difference with [rbc-last-match](https://github.com/NAMeC-SSL/CRAbE/tree/rbc-last-match) is only #67

**Comment by Wanchai290** [comment]
as mentioned at the latest meeting, these commits & identified features will be split to become their own PR.  
I will regroup them all by starting their branch name with `ft-rbc23`, please look forward to these

**Comment by Wanchai290** [comment]
There are some commits for which I cannot create a PR yet, as they're dependent on previous commits:
- 74e8779fcea122b5d5194383c03f8ee92d21b842
- 9385bbc136537d08c76d775b8255dbafa7b19260

Other commits already have their own PR :
- 1acd72f86332b555533b46531276ab219547cc5e with #68

**Pull request closed without merging**
