### PR TITLE
chore: ignore local cfg of vscode and jetbrains IDEs

### PR DESCRIPTION
**Pull request by Wanchai290**

### CODE REVIEW

**Comment by EtienneSchmitz** [comment]
I do not agree with this Pull Request, which adds several entries to the .gitignore file that are not relevant to any Rust project. For instance, it includes entries for Android Studio and F#, among others. 
Previously, JetBrains IDE settings were sufficiently ignored with the .idea/ entry. Therefore, if the goal is to add an ignore entry for VSCode, simply adding .vscode/ should suffice. I believe that each developer working on the project has their own toolchain and should be responsible for what they introduce to the project. 
Lastly, I am not in favor to add in the project a credit of a commercial company for a files like this. 

For me, the gitignore will be like this : 
```.gitignore
# Rust
target/

# Code editor
.idea/
.vscode/
```

Maybe @benjaminchew4 has more lines for rust project specific.

**Comment by Wanchai290** [comment]
setting the commercial thing aside (which I don't see as a problem but idk about this, looked open-source so it was fine to me),

we absolutely have no idea what the ide could generate or even how it works. Someone resolved the problem and made the solution open-source so I'm just using the tools available

**Comment by Wanchai290** [comment]
whatever I'll just close this

**Comment by Wanchai290** [comment]
i've applied ur changes, let's merge this when possible

**Review by EtienneSchmitz — APPROVED** [review]

**Pull request merged**
